config/routes.rb
Rails.application.routes.draw do
  get 'usuarios/new'

  root 'estaticas#home'

  get 'cotiza' => 'estaticas#cotiza'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  resources :usuarios

  match '/cotizacion',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :pickup, :validate => true
  attribute :dropoff, :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Cotización nueva",
      :to => "bicimensajero420@gmail.com",
      :bcc => "champion327@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :nombre, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
								uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to root_path, notice: "Recibimos tu mensaje, en menos de 14 minutos recibes tu cotización"
    else
      flash.now[:error] = 'No se pudo enviar tu mensaje, por favor marcanos al: 55-555-555'
      render :new
    end
  end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def home
  end

  def cotiza
  end

  def acercade
  end

  def faq
  end

  def unete
  end

  def politicas
  end

  def contacto
  end

  def privacidad
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  def show
	@usuario = Usuario.find(params[:id])
  end

  def nueva
  	@usuario = Usuario.new
  end

  def create
  	@usuario = Usuario.new(usuario_params)
  	if @usuario.save
  		flash[:success] = "Bienvenido, " + @usuario.nombre + "."" Comienza a enviar!"
  		redirect_to @usuario
  	else
  		render 'nueva'
  	end
  end

  private

  	def usuario_params
  		params.require(:usuario).permit(:nombre, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper

# Returns the Gravatar for the given user.
  def gravatar_for(usuario)
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: usuario.nombre, class: "gravatar")
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert"></a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, "Cotiza | ") %>

<div class="row">
  <div class="col-md-4 col-md-push-3">
  <h3>Solicita una cotización</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, label: 'Tu nombre es:' %>
    <%= f.input :email, label: 'Tu email porfa', :required => true %>
    <%= f.input :pickup, placeholder: 'Calle, número y colonia.', label: '¿A dónde pasamos por tu paquete?', :as => :text, :required => true %>
    <%= f.input :dropoff, placeholder: 'Calle, número y colonia.', label: '¿A dónde lo llevamos?', :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Solicitar cotización', :class=> "btn btn-primary" %>
    </div>
  <% end %>

  </div>

</div>

app/views/estaticas/acercade.html.erb
<% provide(:title, "acercaDe | ") %>
<h1>Acerca de nosotros</h1>
<p>Aquí se incorporará la sección "Acerca de"</p>

app/views/estaticas/contacto.html.erb
<% provide(:title, "Contacto | ") %>
<h1>Contactanos</h1>
<p>Envianos un mail a:</p>
<li>
	<ul>Negocios: xxx@xxx.com</ul>
</li>

app/views/estaticas/cotiza.html.erb
<% provide(:title, "Cotiza | ") %>

<h1>Checa nuestros precios</h1>
<p>Utiliza nuestra práctica herramienta para cotizar</p>

app/views/estaticas/faq.html.erb
<% provide(:title, "FAQ | ") %>
<h1>F.A.Q.</h1>
<p>Para las preguntas más frecuentes</p>

app/views/estaticas/home.html.erb
<div class="row">

	<div class="center jumbotron padding-top-bottom-100">
		<div class="row">
			<div class="col-lg-12">
  				<%= link_to "Cotiza tu envío", cotizacion_path, class: "btn btn-lg btn-primary margin-topBottom-100", 'data-no-turbolink' => true %>
  			</div>
  		</div>
	</div>

</div>

<div class="row">
	<div class="col-lg-12 center">
		<%= link_to "Chambea con nosotros", unete_path, class: "btn btn-lg btn-success margin-top-100" %>
		<%= link_to "Preguntas frecuentes", faq_path, class: "btn btn-lg btn-success margin-top-100" %>
		<%= link_to "Políticas de envíos", politicas_path, class: "btn btn-lg btn-success margin-top-100" %>
	</div>
</div>

app/views/estaticas/politicas.html.erb
<% provide(:title, "Políticas | ") %>

<meta type="description" content="Find the distance between two places on the map and the shortest route."/>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">

	var location1;
	var location2;
	
	var address1;
	var address2;

	var latlng;
	var geocoder;
	var map;
	
	var distance;
	
	// finds the coordinates for the two locations and calls the showMap() function
	function initialize()
	{
		geocoder = new google.maps.Geocoder(); // creating a new geocode object
		
		// getting the two address values
		address1 = document.getElementById("address1").value;
		address2 = document.getElementById("address2").value;
		
		// finding out the coordinates
		if (geocoder) 
		{
			geocoder.geocode( { 'address': address1}, function(results, status) 
			{
				if (status == google.maps.GeocoderStatus.OK) 
				{
					//location of first address (latitude + longitude)
					location1 = results[0].geometry.location;
				} else 
				{
					alert("Geocode was not successful for the following reason: " + status);
				}
			});
			geocoder.geocode( { 'address': address2}, function(results, status) 
			{
				if (status == google.maps.GeocoderStatus.OK) 
				{
					//location of second address (latitude + longitude)
					location2 = results[0].geometry.location;
					// calling the showMap() function to create and show the map 
					showMap();
				} else 
				{
					alert("Geocode was not successful for the following reason: " + status);
				}
			});
		}
	}
		
	// creates and shows the map
	function showMap()
	{
		// center of the map (compute the mean value between the two locations)
		latlng = new google.maps.LatLng((location1.lat()+location2.lat())/2,(location1.lng()+location2.lng())/2);
		
		// set map options
			// set zoom level
			// set center
			// map type
		var mapOptions = 
		{
			zoom: 1,
			center: latlng,
			
		};
		
		// create a new map object
			// set the div id where it will be shown
			// set the map options
		map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
		
		// show route between the points
		directionsService = new google.maps.DirectionsService();
		directionsDisplay = new google.maps.DirectionsRenderer(
		{
			suppressMarkers: true,
			suppressInfoWindows: true
		});
		directionsDisplay.setMap(map);
		var request = {
			origin:location1, 
			destination:location2,
			travelMode: google.maps.DirectionsTravelMode.BICYCLING
		};
		directionsService.route(request, function(response, status) 
		{
			if (status == google.maps.DirectionsStatus.OK) 
			{
				directionsDisplay.setDirections(response);
				distance = "The distance between the two points on the chosen route is: "+response.routes[0].legs[0].distance.text;
				distance += "<br/>The aproximative biking time is: "+response.routes[0].legs[0].duration.text;
				document.getElementById("distance_road").innerHTML = distance;
			}
		});
		
		// show a line between the two points
		var line = new google.maps.Polyline({
			map: map, 
			path: [location1, location2],
			strokeWeight: 7,
			strokeOpacity: 0.8,
			strokeColor: "#FFAA00"
		});
		
		// create the markers for the two locations		
		var marker1 = new google.maps.Marker({
			map: map, 
			position: location1,
			title: "First location"
		});
		var marker2 = new google.maps.Marker({
			map: map, 
			position: location2,
			title: "Second location"
		});
		
		// create the text to be shown in the infowindows
		var text1 = '<div id="content">'+
				'<h1 id="firstHeading">First location</h1>'+
				'<div id="bodyContent">'+
				'<p>Coordinates: '+location1+'</p>'+
				'<p>Address: '+address1+'</p>'+
				'</div>'+
				'</div>';
				
		var text2 = '<div id="content">'+
			'<h1 id="firstHeading">Second location</h1>'+
			'<div id="bodyContent">'+
			'<p>Coordinates: '+location2+'</p>'+
			'<p>Address: '+address2+'</p>'+
			'</div>'+
			'</div>';
		
		// create info boxes for the two markers
		var infowindow1 = new google.maps.InfoWindow({
			content: text1
		});
		var infowindow2 = new google.maps.InfoWindow({
			content: text2
		});

		// add action events so the info windows will be shown when the marker is clicked
		google.maps.event.addListener(marker1, 'click', function() {
			infowindow1.open(map,marker1);
		});
		google.maps.event.addListener(marker2, 'click', function() {
			infowindow2.open(map,marker1);
		});
		
		// compute distance between the two points
		var R = 6371; 
		var dLat = toRad(location2.lat()-location1.lat());
		var dLon = toRad(location2.lng()-location1.lng()); 
		
		var dLat1 = toRad(location1.lat());
		var dLat2 = toRad(location2.lat());
		
		var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
				Math.cos(dLat1) * Math.cos(dLat1) * 
				Math.sin(dLon/2) * Math.sin(dLon/2); 
		var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
		var d = R * c;
		
		document.getElementById("distance_direct").innerHTML = "<br/>The distance between the two points (in a straight line) is: "+d;
	}
	
	function toRad(deg) 
	{
		return deg * Math.PI/180;
	}
</script>




	<div id="form" style="width:100%; height:20%">
		<table align="center" valign="center">
			<tr>
				<td colspan="7" align="center"><b>Find the distance between two locations</b></td>
			</tr>
			<tr>
				<td colspan="7">&nbsp;</td>
			</tr>
			<tr>
				<td>First address:</td>
				<td>&nbsp;</td>
				<td><input type="text" name="address1" id="address1" size="50"/></td>
				<td>&nbsp;</td>
				<td>Second address:</td>
				<td>&nbsp;</td>
				<td><input type="text" name="address2" id="address2" size="50"/></td>
			</tr>
			<tr>
				<td colspan="7">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="7" align="center"><input type="button" value="Show" onclick="initialize();"/></td>
			</tr>
		</table>
	</div>
	
	<center><div style="width:100%; height:10%" id="distance_road"></div></center>


	<div id="map-container">
	<div id="map_canvas"></div>
	</div>

app/views/estaticas/privacidad.html.erb
<% provide(:title, "Privacidad | ") %>
<h1>Aviso de privacidad</h1>
<p>Para que leas lo que vamos a hacer con tus datos.</p>

app/views/estaticas/unete.html.erb
<% provide(:title, "Únete | ") %>
<h1>Únete a nosotros</h1>
<p>Para chambiar.</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Bicimensajero 2015</p>
  </small>
  <nav>
    <ul>
      <li><h4><%= link_to "Acerca de nosotros", acercade_path %></h4></li>
      <li><h4><%= link_to "Contacto", contacto_path %></h4></li>
      <li><h4><%= link_to "Aviso de privacidad", privacidad_path %></h4></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "bicimensajero", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Crea una cuenta", nuevacuenta_path, id: "login" %></li>
        <li><%= link_to "Ingresa a tu cuenta", '#', id: "login" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>Bicimensajero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2RaCuxr3jZBhU8-ptKe08CduIkhj9Ka8">
  </script>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body>

    <%= render 'layouts/header' %>

    <div class="container-fluid padding-top-200">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @usuario.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Tu registro contiene: <%= pluralize(@usuario.errors.count, "error") %>.
    </div>
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/usuarios/nueva.html.erb
<% provide(:title, "Crea Cuenta | ") %>

<h2>¡Comienza a pedir todo a domicilio el mísmo día!</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :nombre_de_usuario %>
      <%= f.text_field :nombre, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirma tu password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear cuenta gratis", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/usuarios/show.html.erb
<% provide(:title, @usuario.nombre + " | ") %>

<div class="row">

	<aside class="col-md-4">

		<section class="user_info">

			<h3>
				<%= gravatar_for @usuario %>
			</h3>

			<h3>
				<%= @usuario.nombre %>
			</h3>

			<h4><%= @usuario.email %></h4>

		</section>

	</aside>

</div>